// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SelectedWhitespace
{
    internal sealed partial class Vsix
    {
        public const string Id = "SelectedWhitespace.63944e24-4aa2-4d0a-8161-4b7eb9f39831";
        public const string Name = "Whitespace Visualizer - WKN";
        public const string Description = @"Displays whitespace characters (spaces, tabs, line endings) only within selected text. Keep your editor clean while still being able to inspect whitespace when needed.";
        public const string Language = "en-US";
        public const string Version = "1.0.901";
        public const string Author = "Mads Kristensen";
        public const string Tags = "whitespace, spaces, tabs";
        public const bool IsPreview = false;
    }
}
